export const columnInfos = {
  projectsColumnInfo: [{
    columnName: "名称",
    sortable: true,
    isURL: false,
    keyword: "projectName",
    isRouter: true,
    isDate: false,
    targetURL: "/project/",
    paramKeyword: "projectId"
  }, {
    columnName: "平台",
    sortable: false,
    isURL: false,
    keyword: "platform",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "所用语言",
    sortable: false,
    isURL: false,
    keyword: "language",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "地址",
    sortable: false,
    isURL: true,
    keyword: "homepageUrl",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "创建时间",
    sortable: true,
    isURL: false,
    keyword: "createT",
    isRouter: false,
    isDate: true,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "更新时间",
    sortable: true,
    isURL: false,
    keyword: "updateT",
    isRouter: false,
    isDate: true,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "版本",
    sortable: true,
    isURL: false,
    keyword: "latestReleaseN",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "仓库地址",
    sortable: false,
    isURL: true,
    keyword: "repositoryUrl",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }
  ],

  projectColumnInfo: [{
    columnName: "平台",
    sortable: false,
    isURL: false,
    keyword: "platform",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "所用语言",
    sortable: false,
    isURL: false,
    keyword: "language",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "地址",
    sortable: false,
    isURL: true,
    keyword: "homepageUrl",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "创建时间",
    sortable: true,
    isURL: false,
    keyword: "createT",
    isRouter: false,
    isDate: true,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "更新时间",
    sortable: true,
    isURL: false,
    keyword: "updateT",
    isRouter: false,
    isDate: true,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "最新发布版本时间",
    sortable: true,
    isURL: false,
    keyword: "latestReleaseT",
    isRouter: false,
    isDate: true,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "版本",
    sortable: true,
    isURL: false,
    keyword: "latestReleaseN",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "所属仓库",
    sortable: false,
    isURL: false,
    keyword: "repoName",
    isRouter: true,
    isDate: false,
    targetURL: "/repository/",
    paramKeyword: "repositoryId"
  }, {
    columnName: "仓库地址",
    sortable: false,
    isURL: true,
    keyword: "repositoryUrl",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }
  ],

  repositoryColumnInfo: [{
    columnName: "平台",
    sortable: false,
    isURL: false,
    keyword: "hostType",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "所有者",
    sortable: false,
    isURL: false,
    keyword: "repositoryOwner",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "所用语言",
    sortable: false,
    isURL: false,
    keyword: "language",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "地址",
    sortable: false,
    isURL: true,
    keyword: "homepageUrl",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "创建时间",
    sortable: true,
    isURL: false,
    keyword: "createT",
    isRouter: false,
    isDate: true,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "更新时间",
    sortable: true,
    isURL: false,
    keyword: "updateT",
    isRouter: false,
    isDate: true,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "最新push时间",
    sortable: true,
    isURL: false,
    keyword: "latestPushT",
    isRouter: false,
    isDate: true,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "能否fork",
    sortable: false,
    isURL: false,
    keyword: "canFork",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "fork数量",
    sortable: true,
    isURL: false,
    keyword: "forkCount",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "watcher数量",
    sortable: true,
    isURL: false,
    keyword: "watcherCount",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "star数量",
    sortable: true,
    isURL: false,
    keyword: "starCount",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "贡献者数量",
    sortable: true,
    isURL: false,
    keyword: "contributorCount",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "issue数量",
    sortable: true,
    isURL: false,
    keyword: "openIssueCount",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "默认分支",
    sortable: true,
    isURL: false,
    keyword: "defaultBranch",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }
  ],

  repositoriesColumnInfo: [{
    columnName: "名称",
    sortable: true,
    isURL: false,
    keyword: "repositoryName",
    isRouter: true,
    isDate: false,
    targetURL: "/repository/",
    paramKeyword: "repositoryId"
  }, {
    columnName: "平台",
    sortable: false,
    isURL: false,
    keyword: "hostType",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "所有者",
    sortable: false,
    isURL: false,
    keyword: "repositoryOwner",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "所用语言",
    sortable: false,
    isURL: false,
    keyword: "language",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "地址",
    sortable: false,
    isURL: true,
    keyword: "homepageUrl",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "创建时间",
    sortable: true,
    isURL: false,
    keyword: "createT",
    isRouter: false,
    isDate: true,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "更新时间",
    sortable: true,
    isURL: false,
    keyword: "updateT",
    isRouter: false,
    isDate: true,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "能否fork",
    sortable: false,
    isURL: false,
    keyword: "canFork",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "fork数量",
    sortable: true,
    isURL: false,
    keyword: "forkCount",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "watcher数量",
    sortable: true,
    isURL: false,
    keyword: "watcherCount",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "star数量",
    sortable: true,
    isURL: false,
    keyword: "starCount",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "贡献者数量",
    sortable: true,
    isURL: false,
    keyword: "contributorCount",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "issue数量",
    sortable: true,
    isURL: false,
    keyword: "openIssueCount",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }
  ],

  mavenProjectsColumnInfo: [{
    columnName: "artifactId",
    sortable: true,
    isURL: false,
    keyword: "artifactId",
    isRouter: true,
    isDate: false,
    targetURL: "/maven-project/",
    paramKeyword: "projectId"
  }, {
    columnName: "groupId",
    sortable: true,
    isURL: false,
    keyword: "groupId",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "名称",
    sortable: false,
    isURL: false,
    keyword: "name",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "地址",
    sortable: false,
    isURL: true,
    keyword: "url",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "描述信息",
    sortable: false,
    isURL: false,
    keyword: "description",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  },],
  mavenProjectColumnInfo: [{
    columnName: "groupId",
    sortable: true,
    isURL: false,
    keyword: "groupId",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "名称",
    sortable: false,
    isURL: false,
    keyword: "name",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "版本",
    sortable: false,
    isURL: false,
    keyword: "version",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "url",
    sortable: false,
    isURL: true,
    keyword: "url",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  },
  ],

  mavenDependencyColumnInfo: [{
    columnName: "groupId",
    sortable: false,
    isURL: false,
    keyword: "groupId",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "artifactId",
    sortable: false,
    isURL: false,
    keyword: "artifactId",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "版本",
    sortable: false,
    isURL: false,
    keyword: "version",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  },
  ],

  mavenDependencyDiffColumnInfo: [{
    columnName: "groupId",
    sortable: false,
    isURL: false,
    keyword: "groupId",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "artifactId",
    sortable: false,
    isURL: false,
    keyword: "artifactId",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "版本",
    sortable: false,
    isURL: false,
    keyword: "version",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  }, {
    columnName: "变化",
    sortable: false,
    isURL: false,
    keyword: "diff",
    isRouter: false,
    isDate: false,
    targetURL: "",
    paramKeyword: ""
  },],

  rulesColumnInfo:[
    {
      columnName: "相关迁移项目名称",
      sortable: false,
      isURL: false,
      keyword: "projectName",
      isRouter: true ,
      isDate: false,
      targetURL: "/jump-to-out?url=",
      paramKeyword: "projectUrl"
    },
    {
      columnName: "起始commit",
      sortable: false,
      isURL: false,
      keyword: "startCommitBack",
      isRouter: true,
      isDate: false,
      targetURL: "/jump-to-out?url=",
      paramKeyword: "startCommit"
    },
    {
      columnName: "结束commit",
      sortable: false,
      isURL: false,
      keyword: "endCommitBack",
      isRouter: true,
      isDate: false,
      targetURL: "/jump-to-out?url=",
      paramKeyword: "endCommit"
    },
    {
      columnName: "修改文件",
      sortable: false,
      isURL: false,
      keyword: "fileName",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    },
  ]
}

export const colors = {
  additionBackgroundColor: "#9EFF9E",
  decreaseBackgroundColor: "#FF9090",
}